### ISSUE TITLE
Discord: Too slow actions fail aftert interaction times out

### ISSUE THREAD

**Issue by lajp** [Testausserveri/torimies-rs#33]
This could be resolved by adding an intermediate response like "Processing..." or something

This might be related to #31

**Comment by bluelhf** [comment]
There's an ACK signal that can be sent to Discord via the gateway to signal that the interaction's been acknowledged but the response is yet to be generated (resulting in a "Torimies is thinking..." prompt IIRC). If we're not already, we should send that in the interaction immediately.

**Comment by lajp** [comment]
Hmm, haven't heard of this one. Thanks @bluelhf I'll look into it

**Comment by lajp** [comment]
fixed by 7e8624c90bd94bed12de1b4c4859488966544eda
