### ISSUE TITLE
Add command menu to @Torimies_bot in Telegram

### ISSUE THREAD

**Issue by RoyTakanen** [Testausserveri/torimies-rs#36]
I would love to see command menu on @Torimies_bot in Telegram like this:

![image](https://github.com/Testausserveri/torimies-rs/assets/52327670/8d27d7e3-aa18-4c71-8b28-ac9193fa9c45)

This can be done by sending the following message to @BotFather (first run command `/mybots`, select your bot, choose edit bot and finally click edit commands):

```
start - Display start message
help - Display help message
vahti - Add new vahti with /vahti `[url]`
poistavahti - Remove a vahti with /poistavahti `[url]`
```

**Comment by lajp** [comment]
I wonder if this is the same or different to [this](https://docs.rs/teloxide/0.12.2/teloxide/payloads/struct.SetMyCommands.html)

**Comment by lajp** [comment]
If it is the same, then we could just set the commands in `command::telegram::Telegram::init()`

**Comment by lajp** [comment]
> I wonder if this is the same or different to [this](https://docs.rs/teloxide/0.12.2/teloxide/payloads/struct.SetMyCommands.html)

Looks to be the same, I'll push some code to make the bot set the commands automatically and then close this.
